import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#0E2A4A" },
  loading: { flex: 1, alignItems: "center", justifyContent: "center" },
  loadingText: { color: "#FFFFFF", fontSize: 15, fontWeight: "600" },
  screen: { flex: 1, backgroundColor: "#F4F6F8" },
  topBar: { backgroundColor: "#0E2A4A", paddingHorizontal: 10, paddingVertical: 6, flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  topBarControl: { minHeight: 44, justifyContent: "center", paddingHorizontal: 8 },
  topBarActionControl: { alignItems: "flex-end" },
  topBarTitle: { color: "#FFFFFF", fontSize: 23, fontWeight: "800", letterSpacing: -0.4 },
  topBarAction: { color: "#FFFFFF", fontSize: 14, fontWeight: "700" },
  scrollContent: { padding: 14, paddingBottom: 30 },
  welcome: { flex: 1, backgroundColor: "#0E2A4A", padding: 28, justifyContent: "center" },
  brandMark: { width: 74, height: 74, backgroundColor: "#F7F1E2", borderRadius: 22, alignItems: "center", justifyContent: "center", marginBottom: 24 },
  brandDiamond: { color: "#E75850", fontSize: 38 },
  appName: { color: "#FFFFFF", fontSize: 38, fontWeight: "800", letterSpacing: -1 },
  tagline: { color: "#C5D3E4", fontSize: 16, lineHeight: 23, marginTop: 10, marginBottom: 30 },
  welcomeSecondaryButton: { borderWidth: 1, borderColor: "#8FA8C5", borderRadius: 14, paddingVertical: 14, alignItems: "center", marginTop: 7 },
  welcomeSecondaryButtonDisabled: { borderColor: "#365473" },
  welcomeSecondaryButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" },
  libraryLink: { alignSelf: "center", paddingVertical: 11 },
  libraryLinkText: { color: "#B9D9D4", fontSize: 15, fontWeight: "800" },
  helper: { color: "#AFC0D7", fontSize: 13, textAlign: "center", marginTop: 16 },
  completeBanner: { backgroundColor: "#F8E8CF", borderRadius: 16, padding: 18, marginBottom: 16 },
  completeEyebrow: { color: "#966218", fontSize: 11, fontWeight: "800", letterSpacing: 1.1 },
  completeTitle: { color: "#5C3812", fontSize: 21, fontWeight: "800", marginTop: 5 },
  completeCopy: { color: "#75542F", fontSize: 13, marginTop: 5 },
  sectionTitle: { color: "#1B2F49", fontSize: 17, fontWeight: "800", marginBottom: 10 },
  playerCard: { backgroundColor: "#FFFFFF", borderRadius: 13, paddingHorizontal: 12, paddingVertical: 10, marginBottom: 7, borderWidth: 1, borderColor: "#E2E7ED" },
  playerHeader: { flexDirection: "row", alignItems: "center" },
  seatBadge: { width: 30, height: 30, borderRadius: 15, backgroundColor: "#DCEDE9", alignItems: "center", justifyContent: "center" },
  seatText: { color: "#0B655D", fontSize: 13, fontWeight: "800" },
  playerNameBlock: { flex: 1 },
  playerNameRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 5 },
  playerName: { color: "#1A2D46", fontSize: 16, fontWeight: "800" },
  distributorStar: { color: "#0D746A", fontSize: 16, lineHeight: 18 },
  openCardIcon: { width: 17, height: 22, borderRadius: 3, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E75850", alignItems: "center", justifyContent: "center" },
  openCardDiamond: { color: "#E75850", fontSize: 12, fontWeight: "800", lineHeight: 14 },
  openCardCue: { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: "#FCE9E7", borderRadius: 5, paddingRight: 5 },
  openCardLabel: { color: "#B44740", fontSize: 11, fontWeight: "800" },
  remainingStatus: { fontSize: 13, fontWeight: "800", flexShrink: 1 },
  totalBlock: { flexDirection: "row", alignItems: "baseline" },
  playerTotal: { color: "#0B655D", fontSize: 25, fontWeight: "800" },
  totalLimit: { color: "#8390A0", fontSize: 12, marginLeft: 3 },
  progressTrack: { height: 5, backgroundColor: "#E7ECEF", borderRadius: 3, marginTop: 9, overflow: "hidden" },
  progressFill: { height: "100%", backgroundColor: "#0D746A", borderRadius: 3 },
  primaryButton: { backgroundColor: "#0D746A", borderRadius: 14, paddingVertical: 14, alignItems: "center", marginTop: 11 },
  primaryButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" },
  pressed: { opacity: 0.82 },
  secondaryButtonText: { color: "#52677D", fontSize: 14, fontWeight: "700" },
  roundActions: { flexDirection: "row", gap: 6, marginTop: 0 },
  roundAction: { flex: 1, alignItems: "center", paddingVertical: 10 },
  rejoinButton: { borderWidth: 1, borderColor: "#0D746A", borderRadius: 12, alignItems: "center", paddingVertical: 11, marginBottom: 4 },
  rejoinButtonText: { color: "#0D746A", fontSize: 14, fontWeight: "800" },
  historyArea: { marginTop: 6 },
  historyList: { gap: 8 },
  historyCard: { backgroundColor: "#FFFFFF", borderRadius: 14, padding: 14, borderWidth: 1, borderColor: "#E1E6EC" },
  historyRound: { color: "#1A2D46", fontSize: 14, fontWeight: "800", marginBottom: 5 },
  historyEntry: { color: "#58697C", fontSize: 13, lineHeight: 20 },
  modalSafe: { flex: 1, backgroundColor: "#F4F6F8" },
  modalKeyboard: { flex: 1 },
  modalHeader: { paddingHorizontal: 20, paddingVertical: 16, backgroundColor: "#FFFFFF", borderBottomWidth: 1, borderBottomColor: "#E2E7ED", flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
  modalTitle: { color: "#172B43", fontSize: 20, fontWeight: "800" },
  closeText: { color: "#0D746A", fontSize: 14, fontWeight: "800", paddingTop: 4 },
  dangerCloseText: { color: "#B34D48", fontSize: 14, fontWeight: "800", paddingTop: 4 },
  modalContent: { padding: 20, paddingBottom: 46 },
  modalLead: { color: "#53677D", fontSize: 14, lineHeight: 21, marginBottom: 22 },
  formTitle: { color: "#1B2F49", fontSize: 17, fontWeight: "800", marginBottom: 10, marginTop: 4 },
  nameRow: { flexDirection: "row", alignItems: "center", marginBottom: 9, gap: 8 },
  nameInput: { flex: 1, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D9E0E8", borderRadius: 10, paddingHorizontal: 12, paddingVertical: 12, fontSize: 15, color: "#172B43" },
  removeControl: { color: "#B34D48", fontSize: 26, fontWeight: "500", paddingLeft: 1 },
  disabledText: { color: "#C4CCD6" },
  addPlayer: { alignSelf: "flex-start", paddingVertical: 10, marginBottom: 18 },
  addPlayerText: { color: "#0D746A", fontSize: 14, fontWeight: "800" },
  savedPlayersSection: { marginTop: 14, marginBottom: 22 },
  savedPlayersHint: { color: "#617386", fontSize: 13, lineHeight: 19, marginTop: -4, marginBottom: 10 },
  savedPlayersList: { gap: 8 },
  savedPlayerButton: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D9E0E8", borderRadius: 11, paddingHorizontal: 13, paddingVertical: 11, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  savedPlayerButtonDisabled: { backgroundColor: "#F1F3F5", borderColor: "#E4E8ED" },
  savedPlayerName: { color: "#233A55", fontSize: 15, fontWeight: "700" },
  savedPlayerAdd: { color: "#0D746A", fontSize: 22, fontWeight: "800", lineHeight: 22 },
  ruleHint: { color: "#617386", fontSize: 13, lineHeight: 19, marginBottom: 10 },
  rulesToggle: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 10, marginTop: 2 },
  rulesToggleText: { color: "#0D746A", fontSize: 14, fontWeight: "800" },
  rulesContent: { paddingTop: 2 },
  field: { marginBottom: 12 },
  compactField: { marginBottom: 0, marginTop: 10 },
  fieldLabel: { color: "#374B61", fontSize: 13, fontWeight: "700", marginBottom: 6 },
  numberInput: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D9E0E8", borderRadius: 10, paddingHorizontal: 12, paddingVertical: 12, fontSize: 16, color: "#172B43" },
  errorText: { color: "#A53832", fontSize: 14, fontWeight: "700", marginTop: 12 },
  libraryPlayerList: { backgroundColor: "#FFFFFF", borderRadius: 13, borderWidth: 1, borderColor: "#E0E6EC", overflow: "hidden" },
  libraryPlayerName: { color: "#233A55", fontSize: 15, fontWeight: "700", paddingHorizontal: 14, paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: "#E8ECF0" },
  emptyLibraryText: { color: "#617386", fontSize: 14, marginTop: -2 },
  settingsPlayersTitle: { marginTop: 30 },
  managePlayersButton: { alignSelf: "flex-start", paddingVertical: 13 },
  managePlayersButtonText: { color: "#0D746A", fontSize: 14, fontWeight: "800" },
  rejoinList: { gap: 9, marginTop: 4 },
  rejoinPlayerButton: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D9E0E8", borderRadius: 12, paddingHorizontal: 14, paddingVertical: 14, flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  rejoinPlayerButtonDisabled: { backgroundColor: "#F1F3F5", borderColor: "#E4E8ED" },
  rejoinPlayerName: { color: "#233A55", fontSize: 15, fontWeight: "800" },
  rejoinPlayerScore: { color: "#0D746A", fontSize: 13, fontWeight: "800" },
  roundCard: { backgroundColor: "#FFFFFF", borderRadius: 16, padding: 15, marginBottom: 13, borderWidth: 1, borderColor: "#E0E6EC" },
  roundPlayerHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "baseline", marginBottom: 10 },
  roundPlayerName: { color: "#172B43", fontSize: 17, fontWeight: "800" },
  roundPlayerTotal: { color: "#617386", fontSize: 13, fontWeight: "700" },
  kindGrid: { flexDirection: "row", gap: 6 },
  kindButton: { flex: 1, alignItems: "center", paddingVertical: 8, borderRadius: 9, borderWidth: 1 },
  kindButtonWin: { backgroundColor: "#E7F5EC", borderColor: "#78B88A" },
  kindButtonDrop: { backgroundColor: "#FFF0DE", borderColor: "#EFA451" },
  kindButtonMid: { backgroundColor: "#EEF1F4", borderColor: "#B5BEC8" },
  kindButtonFull: { backgroundColor: "#FCE9E7", borderColor: "#E27A72" },
  kindButtonWinSelected: { backgroundColor: "#2F8A52", borderColor: "#2F8A52" },
  kindButtonDropSelected: { backgroundColor: "#DD8119", borderColor: "#DD8119" },
  kindButtonMidSelected: { backgroundColor: "#687582", borderColor: "#687582" },
  kindButtonFullSelected: { backgroundColor: "#C95047", borderColor: "#C95047" },
  kindButtonText: { color: "#31465A", fontSize: 12, fontWeight: "800" },
  kindButtonTextSelected: { color: "#FFFFFF" },
});
