import { Platform, StatusBar, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#0E2A4A" },
  loading: { flex: 1, alignItems: "center", justifyContent: "center" },
  loadingText: { color: "#FFFFFF", fontSize: 15, fontWeight: "600" },
  screen: { flex: 1, backgroundColor: "#F4F6F8" },
  topBar: { backgroundColor: "#0E2A4A", paddingHorizontal: 16, paddingVertical: 10, flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  topBarControl: { minHeight: 44, justifyContent: "center" },
  topBarActionControl: { alignItems: "flex-end", marginRight: -8 },
  topBarTitle: { color: "#FFFFFF", fontSize: 20, fontWeight: "800" },
  topBarAction: { color: "#B9D9D4", fontSize: 14, fontWeight: "800" },
  scrollContent: { padding: 14, paddingBottom: 30 },
  welcome: { flex: 1, backgroundColor: "#0E2A4A", padding: 28, justifyContent: "center" },
  brandMark: { width: 74, height: 74, backgroundColor: "#F7F1E2", borderRadius: 22, alignItems: "center", justifyContent: "center", marginBottom: 24 },
  brandDiamond: { color: "#E75850", fontSize: 38 },
  appName: { color: "#FFFFFF", fontSize: 38, fontWeight: "800", letterSpacing: -1 },
  tagline: { color: "#C5D3E4", fontSize: 16, lineHeight: 23, marginTop: 10, marginBottom: 30 },
  welcomeSecondaryButton: { borderWidth: 1, borderColor: "#8FA8C5", borderRadius: 14, paddingVertical: 14, alignItems: "center", marginTop: 7 },
  welcomeSecondaryButtonDisabled: { borderColor: "#365473" },
  welcomeSecondaryButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" },
  libraryLink: { alignSelf: "center", paddingVertical: 11 },
  libraryLinkText: { color: "#B9D9D4", fontSize: 15, fontWeight: "800" },
  helper: { color: "#AFC0D7", fontSize: 13, textAlign: "center", marginTop: 16 },
  completeBanner: { backgroundColor: "#F8E8CF", borderRadius: 16, padding: 18, marginBottom: 16 },
  completeEyebrow: { color: "#966218", fontSize: 11, fontWeight: "800", letterSpacing: 1.1 },
  completeTitle: { color: "#5C3812", fontSize: 21, fontWeight: "800", marginTop: 5 },
  completeCopy: { color: "#75542F", fontSize: 13, marginTop: 5 },
  sectionTitle: { color: "#1B2F49", fontSize: 17, fontWeight: "800", marginBottom: 10 },
  playerCard: { backgroundColor: "#FFFFFF", borderRadius: 13, paddingHorizontal: 12, paddingVertical: 10, marginBottom: 7, borderWidth: 1, borderColor: "#E2E7ED" },
  playerHeader: { flexDirection: "row", alignItems: "center" },
  seatBadge: { width: 30, height: 30, borderRadius: 15, backgroundColor: "#DCEDE9", alignItems: "center", justifyContent: "center" },
  seatText: { color: "#0B655D", fontSize: 13, fontWeight: "800" },
  playerNameBlock: { flex: 1 },
  playerNameRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 5 },
  playerName: { color: "#1A2D46", fontSize: 16, fontWeight: "800" },
  distributorStar: { color: "#0D746A", fontSize: 16, lineHeight: 18 },
  openCardIcon: { width: 17, height: 22, borderRadius: 3, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E75850", alignItems: "center", justifyContent: "center" },
  openCardDiamond: { color: "#E75850", fontSize: 12, fontWeight: "800", lineHeight: 14 },
  openCardCue: { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: "#FCE9E7", borderRadius: 5, paddingRight: 5 },
  openCardLabel: { color: "#B44740", fontSize: 11, fontWeight: "800" },
  remainingStatus: { fontSize: 13, fontWeight: "800", flexShrink: 1 },
  totalBlock: { flexDirection: "row", alignItems: "baseline" },
  playerTotal: { color: "#0B655D", fontSize: 25, fontWeight: "800" },
  totalLimit: { color: "#8390A0", fontSize: 12, marginLeft: 3 },
  progressTrack: { height: 5, backgroundColor: "#E7ECEF", borderRadius: 3, marginTop: 9, overflow: "hidden" },
  progressFill: { height: "100%", backgroundColor: "#0D746A", borderRadius: 3 },
  primaryButton: { backgroundColor: "#0D746A", borderRadius: 14, paddingVertical: 14, alignItems: "center", marginTop: 11 },
  primaryButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" },
  pressed: { opacity: 0.82 },
  secondaryButtonText: { color: "#52677D", fontSize: 14, fontWeight: "700" },
  roundActions: { flexDirection: "row", gap: 6, marginTop: 0 },
  roundAction: { flex: 1, alignItems: "center", paddingVertical: 10 },
  rejoinButton: { borderWidth: 1, borderColor: "#0D746A", borderRadius: 12, alignItems: "center", paddingVertical: 11, marginBottom: 4 },
  rejoinButtonText: { color: "#0D746A", fontSize: 14, fontWeight: "800" },
  historyArea: { marginTop: 4 },
  historyList: { gap: 8 },
  historyCard: { backgroundColor: "#FFFFFF", borderRadius: 12, padding: 10, shadowColor: "#0E2A4A", shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 5, elevation: 2 },
  historyHeader: { marginBottom: 5 },
  historyRound: { color: "#31465A", fontSize: 13, fontWeight: "800" },
  historyEntries: { flexDirection: "row", flexWrap: "wrap", gap: 4 },
  historyEntry: { width: "48%", flexDirection: "row", alignItems: "center", gap: 7, minHeight: 16 },
  historyEntryThreeColumn: { width: "32%" },
  historyEntryName: { color: "#58697C", fontSize: 12, fontWeight: "500", flexShrink: 1 },
  historySeparator: { color: "#58697C", fontSize: 12, fontWeight: "500" },
  historyScore: { color: "#31465A", fontSize: 12, fontWeight: "800" },
  confirmationOverlay: { flex: 1, justifyContent: "center", backgroundColor: "rgba(14,42,74,0.42)", padding: 24 },
  confirmationCard: { backgroundColor: "#FFFFFF", borderRadius: 16, padding: 20 },
  confirmationTitle: { color: "#172B43", fontSize: 19, fontWeight: "800", marginBottom: 8 },
  confirmationCopy: { color: "#53677D", fontSize: 14, lineHeight: 20, marginBottom: 18 },
  confirmationActions: { flexDirection: "row", gap: 10 },
  confirmationAction: { flex: 1, minHeight: 44, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  confirmationCancel: { borderWidth: 1, borderColor: "#B7C3D0" },
  confirmationContinue: { backgroundColor: "#0D746A" },
  confirmationCancelText: { color: "#374B61", fontSize: 14, fontWeight: "800" },
  confirmationContinueText: { color: "#FFFFFF", fontSize: 14, fontWeight: "800" },
  modalSafe: { flex: 1, backgroundColor: "#0E2A4A", paddingTop: Platform.OS === "android" ? StatusBar.currentHeight ?? 0 : 0 },
  modalKeyboard: { flex: 1, backgroundColor: "#F4F6F8" },
  modalHeader: { paddingHorizontal: 16, paddingVertical: 10, backgroundColor: "#0E2A4A", flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  modalTitle: { color: "#FFFFFF", fontSize: 20, fontWeight: "800" },
  modalCloseControl: { minWidth: 44, minHeight: 44, alignItems: "flex-end", justifyContent: "center", marginRight: -8 },
  closeText: { color: "#B9D9D4", fontSize: 14, fontWeight: "800", paddingTop: 4 },
  dangerCloseText: { color: "#F6C2BD", fontSize: 14, fontWeight: "800", paddingTop: 4 },
  modalContent: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 24 },
  modalLead: { color: "#53677D", fontSize: 14, lineHeight: 20, marginBottom: 14 },
  formTitle: { color: "#1B2F49", fontSize: 17, fontWeight: "800", marginBottom: 8, marginTop: 2 },
  nameRow: { flexDirection: "row", alignItems: "center", marginBottom: 9, gap: 8 },
  nameInput: { flex: 1, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D9E0E8", borderRadius: 10, paddingHorizontal: 12, paddingVertical: 12, fontSize: 15, color: "#172B43" },
  removeControl: { color: "#B34D48", fontSize: 26, fontWeight: "500", paddingLeft: 1 },
  disabledText: { color: "#C4CCD6" },
  addPlayer: { alignSelf: "flex-start", paddingVertical: 8, marginBottom: 12 },
  addPlayerText: { color: "#0D746A", fontSize: 14, fontWeight: "800" },
  savedPlayersSection: { marginTop: 10, marginBottom: 14 },
  savedPlayersHint: { color: "#617386", fontSize: 13, lineHeight: 18, marginTop: -2, marginBottom: 8 },
  savedPlayersList: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  savedPlayerButton: { width: "48%", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D9E0E8", borderRadius: 10, paddingHorizontal: 10, paddingVertical: 7, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  savedPlayerButtonDisabled: { backgroundColor: "#F1F3F5", borderColor: "#E4E8ED" },
  savedPlayerName: { color: "#233A55", fontSize: 14, fontWeight: "700", flexShrink: 1 },
  savedPlayerAdd: { color: "#0D746A", fontSize: 22, fontWeight: "800", lineHeight: 22 },
  ruleHint: { color: "#617386", fontSize: 13, lineHeight: 19, marginBottom: 10 },
  rulesToggle: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 8, marginTop: 2 },
  rulesToggleText: { color: "#0D746A", fontSize: 14, fontWeight: "800" },
  rulesContent: { paddingTop: 2 },
  scoreGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  scoreGridItem: { width: "48%" },
  field: { marginBottom: 10 },
  compactField: { marginBottom: 0, marginTop: 0 },
  fieldLabel: { color: "#374B61", fontSize: 13, fontWeight: "700", marginBottom: 4 },
  numberInput: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D9E0E8", borderRadius: 10, paddingHorizontal: 12, paddingVertical: 12, fontSize: 16, color: "#172B43" },
  compactNumberInput: { paddingVertical: 6, fontSize: 15 },
  errorText: { color: "#A53832", fontSize: 14, fontWeight: "700", marginTop: 12 },
  roundErrorBanner: { backgroundColor: "#FCE9E7", borderBottomWidth: 1, borderBottomColor: "#E27A72", color: "#8F2D28", fontSize: 14, fontWeight: "800", paddingHorizontal: 16, paddingVertical: 9 },
  libraryPlayerList: { backgroundColor: "#FFFFFF", borderRadius: 13, borderWidth: 1, borderColor: "#E0E6EC", overflow: "hidden" },
  libraryPlayerRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: "#E8ECF0" },
  libraryPlayerName: { color: "#233A55", fontSize: 15, fontWeight: "700", paddingHorizontal: 14, paddingVertical: 11 },
  libraryDeleteButton: { minHeight: 44, justifyContent: "center", paddingHorizontal: 14 },
  libraryDeleteText: { color: "#B34D48", fontSize: 13, fontWeight: "800" },
  libraryPlayersTitle: { paddingTop: 10 },
  emptyLibraryText: { color: "#617386", fontSize: 14, marginTop: -2 },
  settingsPlayersTitle: { marginTop: 20 },
  managePlayersButton: { alignSelf: "flex-start", paddingVertical: 10 },
  managePlayersButtonText: { color: "#0D746A", fontSize: 14, fontWeight: "800" },
  rejoinList: { gap: 9, marginTop: 4 },
  rejoinPlayerButton: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D9E0E8", borderRadius: 12, paddingHorizontal: 14, paddingVertical: 14, flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  rejoinPlayerButtonDisabled: { backgroundColor: "#F1F3F5", borderColor: "#E4E8ED" },
  rejoinPlayerName: { color: "#233A55", fontSize: 15, fontWeight: "800" },
  rejoinPlayerScore: { color: "#0D746A", fontSize: 13, fontWeight: "800" },
  roundCard: { backgroundColor: "#FFFFFF", borderRadius: 11, padding: 8, marginBottom: 4, borderWidth: 1, borderColor: "#E0E6EC" },
  roundPlayerHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 4 },
  roundPlayerDetails: { flex: 1, marginRight: 10 },
  roundPlayerName: { color: "#172B43", fontSize: 17, fontWeight: "800" },
  roundPlayerTotal: { color: "#617386", fontSize: 13, fontWeight: "700" },
  roundManualScore: { width: "40%" },
  kindGrid: { flexDirection: "row", gap: 6 },
  kindButton: { flex: 1, alignItems: "center", paddingVertical: 6, borderRadius: 8, borderWidth: 1 },
  kindButtonWin: { backgroundColor: "#E7F5EC", borderColor: "#78B88A" },
  kindButtonDrop: { backgroundColor: "#FFF0DE", borderColor: "#EFA451" },
  kindButtonMid: { backgroundColor: "#EEF1F4", borderColor: "#B5BEC8" },
  kindButtonFull: { backgroundColor: "#FCE9E7", borderColor: "#E27A72" },
  kindButtonWinSelected: { backgroundColor: "#2F8A52", borderColor: "#2F8A52" },
  kindButtonDropSelected: { backgroundColor: "#DD8119", borderColor: "#DD8119" },
  kindButtonMidSelected: { backgroundColor: "#687582", borderColor: "#687582" },
  kindButtonFullSelected: { backgroundColor: "#C95047", borderColor: "#C95047" },
  kindButtonText: { color: "#31465A", fontSize: 12, fontWeight: "800" },
  kindButtonTextSelected: { color: "#FFFFFF" },
});
